In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,1],[2,3,2]])
B = np.array([[2,1,1]])

In [3]:
A

array([[1, 2, 1],
       [2, 3, 2]])

In [4]:
B

array([[2, 1, 1]])

In [5]:
np.add(A,B)

array([[3, 3, 2],
       [4, 4, 3]])

In [6]:
np.subtract(A,B)

array([[-1,  1,  0],
       [ 0,  2,  1]])

In [7]:
np.multiply(A,B)

array([[2, 2, 1],
       [4, 3, 2]])

In [8]:
np.divide(A,B)

array([[0.5, 2. , 1. ],
       [1. , 3. , 2. ]])

In [9]:
np.power(A,2)

array([[1, 4, 1],
       [4, 9, 4]], dtype=int32)

In [10]:
np.power(B,2)

array([[4, 1, 1]], dtype=int32)

In [11]:
np.power(A,B)

array([[1, 2, 1],
       [4, 3, 2]])