In [1]:
import numpy as np

In [2]:
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.array([[1,4,8],[4,9,3]])
array_3d = np.array([[4,3,9],[7,7,6],[6,5,33]])

In [3]:
array_1d[0]

1

In [4]:
array_1d[1]

2

In [5]:
array_1d[-3]

4

In [6]:
array_1d

array([1, 2, 3, 4, 5, 6])

In [7]:
array_2d

array([[1, 4, 8],
       [4, 9, 3]])

In [8]:
array_3d

array([[ 4,  3,  9],
       [ 7,  7,  6],
       [ 6,  5, 33]])

In [9]:
array_1d[1:]

array([2, 3, 4, 5, 6])

In [10]:
array_1d[3:5]

array([4, 5])

In [11]:
array_1d[-3:-1]

array([4, 5])

In [12]:
array_2d

array([[1, 4, 8],
       [4, 9, 3]])

In [13]:
array_2d[1:]

array([[4, 9, 3]])

In [14]:
array_2d[0:]

array([[1, 4, 8],
       [4, 9, 3]])

In [15]:
array_3d

array([[ 4,  3,  9],
       [ 7,  7,  6],
       [ 6,  5, 33]])

In [16]:
array_3d[0:]

array([[ 4,  3,  9],
       [ 7,  7,  6],
       [ 6,  5, 33]])

In [17]:
array_3d[1:]

array([[ 7,  7,  6],
       [ 6,  5, 33]])

In [18]:
array_3d[2:]

array([[ 6,  5, 33]])