In [1]:
import numpy as np

In [2]:
arr = np.array([[2,3,5],[5,4,2],[7,4,2]])

In [3]:
arr

array([[2, 3, 5],
       [5, 4, 2],
       [7, 4, 2]])

In [4]:
np.amin(arr)

2

In [5]:
np.amin(arr,axis=0)

array([2, 3, 2])

In [6]:
np.amin(arr,axis=1)

array([2, 2, 2])

In [7]:
np.max(arr)

7

In [8]:
np.amax(arr,axis=0)

array([7, 4, 5])

In [9]:
np.amax(arr,axis=1)

array([5, 5, 7])

In [10]:
np.median(arr)

4.0

In [11]:
np.mean(arr)

3.7777777777777777

In [12]:
np.std(arr)

1.617802197617893

In [13]:
np.var(arr)

2.617283950617284

In [14]:
np.percentile(arr,50)

4.0

In [15]:
deg = np.array([0,30,45,60,90])

In [16]:
np.sin(deg*np.pi/100)

array([0.        , 0.80901699, 0.98768834, 0.95105652, 0.30901699])

In [17]:
np.cos(deg*np.pi/100)

array([ 1.        ,  0.58778525,  0.15643447, -0.30901699, -0.95105652])

In [18]:
np.tan(deg*np.pi/100)

array([ 0.        ,  1.37638192,  6.31375151, -3.07768354, -0.3249197 ])

In [19]:
'''
arcsin
arccos
arctan
'''

'\narcsin\narccos\narctan\n'

In [20]:
np.floor(arr)

array([[2., 3., 5.],
       [5., 4., 2.],
       [7., 4., 2.]])